# Generated by Django 5.2.5 on 2025-10-10 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shopping_App', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
