# Generated by Django 5.2.5 on 2025-10-14 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shopping_App', '0003_alter_transaction_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(blank=True, choices=[('ELECTRONICS', 'Electronics'), ('GROCERIES', 'Groceries'), ('CLOTHINGS', 'Clothings'), ('CARS', 'Cars'), ('ACCESSORY', 'Accessory'), ('PHONES', 'Phones'), ('OTHERS', 'Others')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
