# Generated by Django 5.2.5 on 2025-10-14 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shopping_App', '0004_alter_products_category_alter_transaction_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(upload_to='img/'),
        ),
    ]
