# Generated by Django 5.2.5 on 2025-10-14 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shopping_App', '0005_alter_products_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(upload_to='products/'),
        ),
    ]
