# Generated by Django 5.2.5 on 2025-10-15 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreUsers', '0002_customusers_otp_code_customusers_otp_expiry_otptoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='otp_token',
            field=models.CharField(default='99b4ad', max_length=6),
        ),
    ]
