# Generated by Django 5.2.5 on 2025-10-18 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreUsers', '0003_alter_otptoken_otp_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customusers',
            name='otp_code',
        ),
        migrations.RemoveField(
            model_name='customusers',
            name='otp_expiry',
        ),
        migrations.DeleteModel(
            name='OtpToken',
        ),
    ]
